name: Run Prime Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1' # Specify the GraalVM version
          java-version: '17' # Use Java 17

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile and run Java benchmark
        run: |
          cd benchmarks/java
          javac PrimeBenchmark.java
          java PrimeBenchmark > ../../results/java_result.json

      - name: Run Python benchmark
        run: python3 benchmarks/python/prime_benchmark.py > results/python_result.json

      - name: Compile and run C++ benchmark
        run: |
          g++ -o benchmarks/cpp/PrimeBenchmark benchmarks/cpp/PrimeBenchmark.cpp
          ./benchmarks/cpp/PrimeBenchmark > results/cpp_result.json

      - name: Run JavaScript benchmark
        run: node benchmarks/js/prime_benchmark.js > results/js_result.json

      - name: Aggregate results
        run: |
          echo "# Benchmark Results" > results_summary.md
          echo "" >> results_summary.md
          echo "| Language   | Time (ns)         |" >> results_summary.md
          echo "|------------|-------------------|" >> results_summary.md
          for file in results/*.json; do
            lang=$(basename $file _result.json)
            time=$(grep -oP '"time_ns": \d+' $file | awk '{print $2}')
            echo "| ${lang^}      | ${time} ns       |" >> results_summary.md
          done

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add results_summary.md
          git commit -m "Update benchmark results"
          git push