name: Run Prime Benchmarks

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Create result files
        run: |
          mkdir -p results
          touch results/java_result.json
          touch results/python_result.json
          touch results/cpp_result.json
          touch results/js_result.json
          touch results/java_graalvm_result.json
          touch results/python_pypy_result.json
          touch results/js_graalvm_result.json

      # Original Java benchmark
      - name: Compile and run Java benchmark
        run: |
          cd benchmarks/java
          javac PrimeBenchmark.java
          java PrimeBenchmark > ../../results/java_result.json

      # Original Python benchmark
      - name: Run Python benchmark
        run: python3 benchmarks/python/prime_benchmark.py > results/python_result.json

      # Original JavaScript benchmark
      - name: Run JavaScript benchmark
        run: node benchmarks/js/prime_benchmark.js > results/js_result.json

      # Optimized Java benchmark using GraalVM Native Image
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1' # Specify the GraalVM version
          java-version: '17' # Use Java 17

      - name: Install Native Image
        run: gu install native-image

      - name: Compile and run Java benchmark with GraalVM Native Image
        run: |
          cd benchmarks/java
          javac PrimeBenchmark.java
          native-image --no-fallback PrimeBenchmark
          cd ../../
          ./benchmarks/java/primebenchmark > results/java_graalvm_result.json

      # Optimized Python benchmark using PyPy
      # Set up PyPy
      - name: Set up PyPy
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10'

      - name: Run Python benchmark with PyPy
        run: pypy3 benchmarks/python/prime_benchmark.py > results/python_pypy_result.json

      # Optimized JavaScript benchmark using GraalVM JavaScript engine
      - name: Run JavaScript benchmark with GraalVM
        run: js benchmarks/js/prime_benchmark.js > results/js_graalvm_result.json

      # Compile and run C++ benchmark with optimizations
      - name: Compile and run C++ benchmark
        run: |
          g++ -O3 -march=native -flto -o benchmarks/cpp/PrimeBenchmark benchmarks/cpp/PrimeBenchmark.cpp
          ./benchmarks/cpp/PrimeBenchmark > results/cpp_result.json

      # Generate Markdown Report
      - name: Generate Markdown Report
        run: |
          javac MarkdownGenerator.java
          java MarkdownGenerator

      # Commit results
      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add results_summary.md
          git commit -m "Update benchmark results"
          git push