name: Run Prime Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1' # Specify the GraalVM version
          java-version: '17' # Use Java 17

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile and run Java benchmark
        run: |
          cd benchmarks/java
          javac PrimeBenchmark.java
          java PrimeBenchmark

      - name: Run Python benchmark
        run: python3 benchmarks/python/prime_benchmark.py

      - name: Compile and run C++ benchmark
        run: |
          g++ -o benchmarks/cpp/PrimeBenchmark benchmarks/cpp/PrimeBenchmark.cpp
          ./benchmarks/cpp/PrimeBenchmark

      - name: Run JavaScript benchmark
        run: node benchmarks/js/prime_benchmark.js